# -*- coding: utf-8 -*-
"""Moringa_Data_Science_Prep_W1_Independent_Project_2019_06_Troye_Gilbert_Python_Notebook

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uEl6sI0mbpjgheEa9vtQQ_vCUomGxm9B

#Python Programming
"""

#Takes two values from a user and converts to kilograms.

x = float(input("Enter first value in pounds"))
y = float(input("Enter second value pounds"))
z = 0.453592
print("The first value in kgs is " ,round(x*z,2))
print("The second value in kgs" ,round(y*z,2 ))

# The sum of the values
sum = x + y
print("The sum of the values is", sum)

# The average of the values
average = sum/2
print("The average of the values is", average)

# The difference of the values
difference = x - y
print("The difference of the two values is", difference)

# The quotient when one value is divides
quotient = x // y
print("The quotient is", quotient )

# If odd or even
if (x,y % 2) == 0:
  print("{0} is Even")
else:
  print("{0} is Odd")